version: '3'

services:
  api:
    build: .
    ports:
    - ${VRPersistenceApiPort}:5000
    environment:
      VRPersistenceDbHost: "${VRPersistenceDbHost}"
      VRPersistenceDbPort: "${VRPersistenceDbPort}"
      VRPersistenceDbName: "${VRPersistenceDbName}"
      VRPersistenceDbUsername: "${VRPersistenceDbUsername}"
      VRPersistenceDbPassword: "${VRPersistenceDbPassword}"
    
    depends_on:
      db:
        condition: service_healthy
  db:
    image: library/postgres:13.0
    ports:
      - ${VRPersistenceDbPort}:5432
    environment:
      POSTGRES_DB: "${VRPersistenceDbName}"
      POSTGRES_USER: "${VRPersistenceDbUsername}"
      POSTGRES_PASSWORD: "${VRPersistenceDbPassword}"
      
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${VRPersistenceDbUsername}" ]
      interval: 10s
      timeout: 5s
      retries: 5